  version: '3'

  services:

    db:
      image: mongo:latest
      container_name: fastmongo-db
      ports:
        - "27017:27017"
      environment:
        # TODO automatic without hardcode
        MONGO_INITDB_DATABASE: temp_fastmongo_db 
        MONGO_INITDB_ROOT_USERNAME: temp_fastmongo_user
        MONGO_INITDB_ROOT_PASSWORD: temp_fastmongo_pass
      command: mongod --bind_ip 127.0.0.1 
      volumes:
        - mongo-data:/data/db

    web:
      build: .
      container_name: fastmongo-web
      restart: always
      volumes:
        - ./src/:/app/src/
      ports:
        - "8000:8000"
      depends_on:
        - db


  volumes:
    mongo-data:
